/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package js_room_booking;

import java.io.*;
import java.util.*;
import javax.swing.*;

/**
 * @author Conan
 */
public class B_Search_View_Modify extends javax.swing.JFrame {        
    
    public B_Search_View_Modify() {
        initComponents();
        
        //unable edit in text field
        RoomIDTxt.setEditable(false);
        FromDateTxt.setEditable(false);
        ToDateTxt.setEditable(false);
        TotalDayTxt.setEditable(false);
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SearchViewModifyLab = new javax.swing.JLabel();
        BookIDLab = new javax.swing.JLabel();
        BookIDTxt = new javax.swing.JTextField();
        NameLab = new javax.swing.JLabel();
        NameTxt = new javax.swing.JTextField();
        ICLab = new javax.swing.JLabel();
        ICTxt = new javax.swing.JTextField();
        PHNumLab = new javax.swing.JLabel();
        PHNumTxt = new javax.swing.JTextField();
        EmailLab = new javax.swing.JLabel();
        RoomIDLab = new javax.swing.JLabel();
        EmailTxt = new javax.swing.JTextField();
        RoomIDTxt = new javax.swing.JTextField();
        FromDateLab = new javax.swing.JLabel();
        FromDateTxt = new javax.swing.JTextField();
        ToDtaeLab = new javax.swing.JLabel();
        ToDateTxt = new javax.swing.JTextField();
        BackBut = new javax.swing.JButton();
        TotalDayLab = new javax.swing.JLabel();
        TotalDayTxt = new javax.swing.JTextField();
        SearchBut = new javax.swing.JButton();
        UpdateBut = new javax.swing.JButton();
        BookingLab = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        SearchViewModifyLab.setFont(new java.awt.Font("Neue Haas Grotesk Text Pro", 1, 36)); // NOI18N
        SearchViewModifyLab.setText("Search & View & Modify");

        BookIDLab.setFont(new java.awt.Font("Neue Haas Grotesk Text Pro", 1, 18)); // NOI18N
        BookIDLab.setText("Book ID :");

        BookIDTxt.setFont(new java.awt.Font("Neue Haas Grotesk Text Pro", 0, 18)); // NOI18N

        NameLab.setFont(new java.awt.Font("Neue Haas Grotesk Text Pro", 1, 18)); // NOI18N
        NameLab.setText("Name :");

        NameTxt.setFont(new java.awt.Font("Neue Haas Grotesk Text Pro", 0, 14)); // NOI18N

        ICLab.setFont(new java.awt.Font("Neue Haas Grotesk Text Pro", 1, 18)); // NOI18N
        ICLab.setText("IC :");

        ICTxt.setFont(new java.awt.Font("Neue Haas Grotesk Text Pro", 0, 14)); // NOI18N

        PHNumLab.setFont(new java.awt.Font("Neue Haas Grotesk Text Pro", 1, 18)); // NOI18N
        PHNumLab.setText("PH Number :");

        PHNumTxt.setFont(new java.awt.Font("Neue Haas Grotesk Text Pro", 0, 14)); // NOI18N

        EmailLab.setFont(new java.awt.Font("Neue Haas Grotesk Text Pro", 1, 18)); // NOI18N
        EmailLab.setText("Email :");

        RoomIDLab.setFont(new java.awt.Font("Neue Haas Grotesk Text Pro", 1, 18)); // NOI18N
        RoomIDLab.setText("Room ID :");

        EmailTxt.setFont(new java.awt.Font("Neue Haas Grotesk Text Pro", 0, 14)); // NOI18N

        RoomIDTxt.setFont(new java.awt.Font("Neue Haas Grotesk Text Pro", 0, 14)); // NOI18N

        FromDateLab.setFont(new java.awt.Font("Neue Haas Grotesk Text Pro", 1, 18)); // NOI18N
        FromDateLab.setText("From Date :");

        FromDateTxt.setFont(new java.awt.Font("Neue Haas Grotesk Text Pro", 0, 14)); // NOI18N

        ToDtaeLab.setFont(new java.awt.Font("Neue Haas Grotesk Text Pro", 1, 18)); // NOI18N
        ToDtaeLab.setText("To Date :");

        ToDateTxt.setFont(new java.awt.Font("Neue Haas Grotesk Text Pro", 0, 14)); // NOI18N

        BackBut.setBackground(new java.awt.Color(0, 0, 0));
        BackBut.setFont(new java.awt.Font("Neue Haas Grotesk Text Pro", 1, 14)); // NOI18N
        BackBut.setForeground(new java.awt.Color(255, 255, 255));
        BackBut.setText("BACK");
        BackBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButActionPerformed(evt);
            }
        });

        TotalDayLab.setFont(new java.awt.Font("Neue Haas Grotesk Text Pro", 1, 18)); // NOI18N
        TotalDayLab.setText("Total Day :");

        TotalDayTxt.setFont(new java.awt.Font("Neue Haas Grotesk Text Pro", 0, 14)); // NOI18N

        SearchBut.setFont(new java.awt.Font("Neue Haas Grotesk Text Pro", 3, 14)); // NOI18N
        SearchBut.setText("SEARCH");
        SearchBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchButActionPerformed(evt);
            }
        });

        UpdateBut.setBackground(new java.awt.Color(233, 225, 117));
        UpdateBut.setFont(new java.awt.Font("Neue Haas Grotesk Text Pro", 3, 18)); // NOI18N
        UpdateBut.setForeground(new java.awt.Color(116, 116, 35));
        UpdateBut.setText("Update");
        UpdateBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateButActionPerformed(evt);
            }
        });

        BookingLab.setFont(new java.awt.Font("Neue Haas Grotesk Text Pro", 1, 36)); // NOI18N
        BookingLab.setText("Booking");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addComponent(BookingLab))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(SearchViewModifyLab))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(TotalDayLab)
                                    .addComponent(ToDtaeLab)
                                    .addComponent(FromDateLab)
                                    .addComponent(RoomIDLab)
                                    .addComponent(EmailLab)
                                    .addComponent(PHNumLab)
                                    .addComponent(ICLab)
                                    .addComponent(NameLab)
                                    .addComponent(BookIDLab))
                                .addGap(40, 40, 40)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(NameTxt)
                                    .addComponent(ICTxt)
                                    .addComponent(PHNumTxt)
                                    .addComponent(EmailTxt)
                                    .addComponent(RoomIDTxt)
                                    .addComponent(FromDateTxt)
                                    .addComponent(ToDateTxt)
                                    .addComponent(TotalDayTxt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(BookIDTxt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(67, 67, 67))
                            .addComponent(SearchBut, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addComponent(BackBut)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(159, 159, 159)
                        .addComponent(UpdateBut)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(SearchViewModifyLab)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BookingLab)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BookIDLab)
                    .addComponent(BookIDTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SearchBut)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NameLab)
                    .addComponent(NameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ICLab)
                    .addComponent(ICTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PHNumLab)
                    .addComponent(PHNumTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EmailLab)
                    .addComponent(EmailTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RoomIDLab)
                    .addComponent(RoomIDTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FromDateLab)
                    .addComponent(FromDateTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ToDtaeLab)
                    .addComponent(ToDateTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TotalDayLab)
                    .addComponent(TotalDayTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(UpdateBut)
                .addGap(25, 25, 25)
                .addComponent(BackBut))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SearchButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchButActionPerformed
              
        try
        {
            File file = new File("booking_2.txt");
            Scanner s = new Scanner(file);
            String BookID = BookIDTxt.getText();
            
            while (s.hasNext())
            {
                String line = s.nextLine();
                
                //read book id in the file
                if (line.contains(BookID))
                {
                    //line = selected row
                    //System.out.println(line);
                    String [] split = line.split(",");
                    
                    //print data
                    NameTxt.setText(split[1]);
                    ICTxt.setText(split[2]);
                    PHNumTxt.setText(split[3]);
                    EmailTxt.setText(split[4]);
                    RoomIDTxt.setText(split[5]);
                    FromDateTxt.setText(split[6]);
                    ToDateTxt.setText(split[7]);
                    TotalDayTxt.setText(split[8]);
                }
            }
        }
        catch (Exception e)
        {
            System.out.println("Error");
        }        
    }//GEN-LAST:event_SearchButActionPerformed

    private void UpdateButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateButActionPerformed
        //get data from text feild
        String book_id = BookIDTxt.getText();
        
        String empty = "";
        if (book_id.equals(empty))
        {
            JOptionPane.showMessageDialog(null, "Please enter Book ID !!!", "Error Message", JOptionPane.ERROR_MESSAGE);
        }
        
        else{
            //get data from text feild
            String name = NameTxt.getText();
            String ic = ICTxt.getText();
            String phnum = PHNumTxt.getText();
            String email = EmailTxt.getText();

            //temporary array to hold the data that is read from file
            ArrayList<String> tempArray = new ArrayList<>();

            try //(FileReader fr = new FileReader("booking_2.txt"))
            {

                File file = new File("booking_2.txt");
                Scanner s = new Scanner(file);
                while(s.hasNext())
                {
                    String line = s.nextLine();

                    if (line.contains(book_id))
                    {                        
                        String [] split = line.split(",");
                        //add the old data and new data into temArray
                        tempArray.add
                        (
                            split[0] +","+
                            name +","+
                            ic +","+
                            phnum +","+
                            email +","+
                            split[5] +","+ 
                            split[6] +","+
                            split[7] +","+ 
                            split[8]
                        );
                    }
                    else
                    {
                        //if book id not match, add line
                        tempArray.add(line);
                    }
                }
            }
            catch (Exception e)
            {
                System.out.println("Error_3");
            }


            //open Print Writer to write the data intempArray back to file
            try (PrintWriter pr = new PrintWriter("booking_2.txt"))
            {
                for (String str : tempArray)
                {
                    //write all data in tempArray back to file 
                    //line bby line
                    pr.println(str);
                }
                //show message
                JOptionPane.showMessageDialog(null, "Customer detail has been updated!!!");

                //when done close file
                pr.close();
                
                //empty text feild
                BookIDTxt.setText("");
                NameTxt.setText(""); 
                ICTxt.setText("");
                PHNumTxt.setText("");
                EmailTxt.setText("");
                RoomIDTxt.setText("");
                FromDateTxt.setText("");
                ToDateTxt.setText("");
                TotalDayTxt.setText(""); 
            }
            catch (Exception e)
            {
                System.out.println("Error_1");
            }
        }
        
    }//GEN-LAST:event_UpdateButActionPerformed

    
    private void BackButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButActionPerformed
        this.setVisible(false);
        ManageRoomBooking mrb = new ManageRoomBooking();
        mrb.setVisible(true);
        dispose();
    }//GEN-LAST:event_BackButActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(B_Search_View_Modify.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(B_Search_View_Modify.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(B_Search_View_Modify.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(B_Search_View_Modify.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new B_Search_View_Modify().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackBut;
    private javax.swing.JLabel BookIDLab;
    private javax.swing.JTextField BookIDTxt;
    private javax.swing.JLabel BookingLab;
    private javax.swing.JLabel EmailLab;
    private javax.swing.JTextField EmailTxt;
    private javax.swing.JLabel FromDateLab;
    private javax.swing.JTextField FromDateTxt;
    private javax.swing.JLabel ICLab;
    private javax.swing.JTextField ICTxt;
    private javax.swing.JLabel NameLab;
    private javax.swing.JTextField NameTxt;
    private javax.swing.JLabel PHNumLab;
    private javax.swing.JTextField PHNumTxt;
    private javax.swing.JLabel RoomIDLab;
    private javax.swing.JTextField RoomIDTxt;
    private javax.swing.JButton SearchBut;
    private javax.swing.JLabel SearchViewModifyLab;
    private javax.swing.JTextField ToDateTxt;
    private javax.swing.JLabel ToDtaeLab;
    private javax.swing.JLabel TotalDayLab;
    private javax.swing.JTextField TotalDayTxt;
    private javax.swing.JButton UpdateBut;
    // End of variables declaration//GEN-END:variables
}
