/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package js_room_booking;

import java.io.*;
import java.util.*;
import javax.swing.*;
        
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.temporal.ChronoUnit;

public class BookRoom extends javax.swing.JFrame {

    /**
     * Creates new form BookRoom
     */
    public BookRoom() {
        initComponents();
        
        //unable edit in text field
        RoomIDTxt.setEditable(false);
        FromDateTxt.setEditable(false);
        ToDateTxt.setEditable(false);
        TotalDayTxt.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BookRoomLab = new javax.swing.JLabel();
        NameLab = new javax.swing.JLabel();
        ICLab = new javax.swing.JLabel();
        PhNumLab = new javax.swing.JLabel();
        EmailLab = new javax.swing.JLabel();
        RoomIDLab = new javax.swing.JLabel();
        ICTxt = new javax.swing.JTextField();
        PhNumTxt = new javax.swing.JTextField();
        EmailTxt = new javax.swing.JTextField();
        RoomIDTxt = new javax.swing.JTextField();
        FromDateLab = new javax.swing.JLabel();
        BackBookRoomBut = new javax.swing.JButton();
        ClearBut = new javax.swing.JButton();
        BookBut = new javax.swing.JButton();
        TotalDayLab = new javax.swing.JLabel();
        TotalDayTxt = new javax.swing.JTextField();
        NameTxt = new javax.swing.JTextField();
        BookIDLab = new javax.swing.JLabel();
        BookIDTxt = new javax.swing.JTextField();
        FromDateTxt = new javax.swing.JTextField();
        FromDateBut = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        ToDateTxt = new javax.swing.JTextField();
        ToDateBut = new javax.swing.JButton();
        TotalDayBut = new javax.swing.JButton();
        ComfirmRoomBut = new javax.swing.JButton();
        RoomIDComboBox = new javax.swing.JComboBox<>();
        CheckRoomBut = new javax.swing.JButton();
        CheckBookIDBut = new javax.swing.JButton();
        FromDate_chooser = new com.toedter.calendar.JDateChooser();
        ToDate_chooser = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BookRoomLab.setFont(new java.awt.Font("Neue Haas Grotesk Text Pro", 1, 36)); // NOI18N
        BookRoomLab.setText("Book Room");

        NameLab.setFont(new java.awt.Font("Neue Haas Grotesk Text Pro", 1, 18)); // NOI18N
        NameLab.setText("Name :");

        ICLab.setFont(new java.awt.Font("Neue Haas Grotesk Text Pro", 1, 18)); // NOI18N
        ICLab.setText("IC :");

        PhNumLab.setFont(new java.awt.Font("Neue Haas Grotesk Text Pro", 1, 18)); // NOI18N
        PhNumLab.setText("PH Number :");

        EmailLab.setFont(new java.awt.Font("Neue Haas Grotesk Text Pro", 1, 18)); // NOI18N
        EmailLab.setText("Email :");

        RoomIDLab.setFont(new java.awt.Font("Neue Haas Grotesk Text Pro", 1, 18)); // NOI18N
        RoomIDLab.setText("Room ID :");

        ICTxt.setFont(new java.awt.Font("Neue Haas Grotesk Text Pro", 0, 14)); // NOI18N

        PhNumTxt.setFont(new java.awt.Font("Neue Haas Grotesk Text Pro", 0, 14)); // NOI18N

        EmailTxt.setFont(new java.awt.Font("Neue Haas Grotesk Text Pro", 0, 14)); // NOI18N

        RoomIDTxt.setFont(new java.awt.Font("Neue Haas Grotesk Text Pro", 0, 14)); // NOI18N

        FromDateLab.setFont(new java.awt.Font("Neue Haas Grotesk Text Pro", 1, 18)); // NOI18N
        FromDateLab.setText("From Date :");

        BackBookRoomBut.setBackground(new java.awt.Color(0, 0, 0));
        BackBookRoomBut.setFont(new java.awt.Font("Neue Haas Grotesk Text Pro", 1, 14)); // NOI18N
        BackBookRoomBut.setForeground(new java.awt.Color(255, 255, 255));
        BackBookRoomBut.setText("BACK");
        BackBookRoomBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackBookRoomButActionPerformed(evt);
            }
        });

        ClearBut.setBackground(new java.awt.Color(0, 153, 204));
        ClearBut.setFont(new java.awt.Font("Neue Haas Grotesk Text Pro", 3, 18)); // NOI18N
        ClearBut.setForeground(new java.awt.Color(58, 58, 131));
        ClearBut.setText("CLEAR");
        ClearBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearButActionPerformed(evt);
            }
        });

        BookBut.setBackground(new java.awt.Color(36, 194, 36));
        BookBut.setFont(new java.awt.Font("Neue Haas Grotesk Text Pro", 3, 18)); // NOI18N
        BookBut.setForeground(new java.awt.Color(124, 124, 34));
        BookBut.setText("BOOK");
        BookBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BookButActionPerformed(evt);
            }
        });

        TotalDayLab.setFont(new java.awt.Font("Neue Haas Grotesk Text Pro", 1, 18)); // NOI18N
        TotalDayLab.setText("Total Day :");

        TotalDayTxt.setFont(new java.awt.Font("Neue Haas Grotesk Text Pro", 0, 14)); // NOI18N

        NameTxt.setFont(new java.awt.Font("Neue Haas Grotesk Text Pro", 0, 14)); // NOI18N

        BookIDLab.setFont(new java.awt.Font("Neue Haas Grotesk Text Pro", 1, 18)); // NOI18N
        BookIDLab.setText("Book ID :");

        BookIDTxt.setFont(new java.awt.Font("Neue Haas Grotesk Text Pro", 0, 14)); // NOI18N

        FromDateTxt.setFont(new java.awt.Font("Neue Haas Grotesk Text Pro", 0, 14)); // NOI18N

        FromDateBut.setBackground(new java.awt.Color(153, 153, 255));
        FromDateBut.setFont(new java.awt.Font("Neue Haas Grotesk Text Pro", 3, 14)); // NOI18N
        FromDateBut.setForeground(new java.awt.Color(97, 94, 94));
        FromDateBut.setText("Date Select");
        FromDateBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FromDateButActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Neue Haas Grotesk Text Pro", 1, 18)); // NOI18N
        jLabel1.setText("To Date:");

        ToDateTxt.setFont(new java.awt.Font("Neue Haas Grotesk Text Pro", 0, 14)); // NOI18N

        ToDateBut.setBackground(new java.awt.Color(153, 153, 255));
        ToDateBut.setFont(new java.awt.Font("Neue Haas Grotesk Text Pro", 3, 14)); // NOI18N
        ToDateBut.setForeground(new java.awt.Color(97, 94, 94));
        ToDateBut.setText("Date Select");
        ToDateBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ToDateButActionPerformed(evt);
            }
        });

        TotalDayBut.setBackground(new java.awt.Color(153, 153, 255));
        TotalDayBut.setFont(new java.awt.Font("Neue Haas Grotesk Text Pro", 3, 14)); // NOI18N
        TotalDayBut.setForeground(new java.awt.Color(97, 94, 94));
        TotalDayBut.setText("Day");
        TotalDayBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TotalDayButActionPerformed(evt);
            }
        });

        ComfirmRoomBut.setBackground(new java.awt.Color(153, 153, 255));
        ComfirmRoomBut.setFont(new java.awt.Font("Neue Haas Grotesk Text Pro", 3, 14)); // NOI18N
        ComfirmRoomBut.setForeground(new java.awt.Color(97, 94, 94));
        ComfirmRoomBut.setText("Confirm");
        ComfirmRoomBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComfirmRoomButActionPerformed(evt);
            }
        });

        RoomIDComboBox.setFont(new java.awt.Font("Neue Haas Grotesk Text Pro", 1, 14)); // NOI18N
        RoomIDComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "J01", "J02", "J03", "J04", "J05", "J06", "J07", "J08", "J09", "J10", "S01", "S02", "S03", "S04", "S05", "S06", "S07", "S08", "S09", "S10" }));

        CheckRoomBut.setBackground(new java.awt.Color(153, 153, 255));
        CheckRoomBut.setFont(new java.awt.Font("Neue Haas Grotesk Text Pro", 3, 14)); // NOI18N
        CheckRoomBut.setForeground(new java.awt.Color(97, 94, 94));
        CheckRoomBut.setText("Check");
        CheckRoomBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckRoomButActionPerformed(evt);
            }
        });

        CheckBookIDBut.setBackground(new java.awt.Color(153, 153, 255));
        CheckBookIDBut.setFont(new java.awt.Font("Neue Haas Grotesk Text Pro", 3, 14)); // NOI18N
        CheckBookIDBut.setForeground(new java.awt.Color(97, 94, 94));
        CheckBookIDBut.setText("Check");
        CheckBookIDBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckBookIDButActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(BookRoomLab))
                    .addComponent(BackBookRoomBut)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(TotalDayLab)
                                        .addGap(46, 46, 46)
                                        .addComponent(TotalDayTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(TotalDayBut)
                                        .addGap(11, 11, 11))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(ToDateTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(FromDateTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGap(39, 39, 39)
                                                        .addComponent(FromDateBut))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGap(37, 37, 37)
                                                        .addComponent(ToDateBut))))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(RoomIDLab)
                                                .addGap(46, 46, 46)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(RoomIDTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(CheckRoomBut))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(RoomIDComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(ComfirmRoomBut)
                                                        .addGap(11, 11, 11))))))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(181, 181, 181))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(FromDateLab)
                                        .addGap(181, 181, 181))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(ICLab)
                                    .addComponent(NameLab)
                                    .addComponent(PhNumLab)
                                    .addComponent(EmailLab)
                                    .addComponent(BookIDLab))
                                .addGap(46, 46, 46)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(FromDate_chooser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(ICTxt)
                                            .addComponent(PhNumTxt)
                                            .addComponent(EmailTxt)
                                            .addComponent(NameTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                                            .addComponent(BookIDTxt))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(CheckBookIDBut))
                                    .addComponent(ToDate_chooser, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(30, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(ClearBut)
                .addGap(40, 40, 40)
                .addComponent(BookBut)
                .addGap(108, 108, 108))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BookRoomLab)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BookIDLab)
                    .addComponent(BookIDTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CheckBookIDBut))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NameLab)
                    .addComponent(NameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ICLab)
                    .addComponent(ICTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PhNumLab)
                    .addComponent(PhNumTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EmailLab)
                    .addComponent(EmailTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(FromDateLab)
                    .addComponent(FromDate_chooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FromDateBut)
                    .addComponent(FromDateTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(ToDate_chooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ToDateBut)
                    .addComponent(ToDateTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TotalDayTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TotalDayLab)
                    .addComponent(TotalDayBut))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RoomIDLab)
                    .addComponent(ComfirmRoomBut)
                    .addComponent(RoomIDComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RoomIDTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CheckRoomBut))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ClearBut)
                    .addComponent(BookBut))
                .addGap(3, 3, 3)
                .addComponent(BackBookRoomBut))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ClearButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearButActionPerformed
        //Clear all data inside text field
        this.BookIDTxt.setText("");
        this.NameTxt.setText("");
        this.ICTxt.setText("");
        this.PhNumTxt.setText("");
        this.EmailTxt.setText("");
        this.RoomIDTxt.setText("");
        this.FromDateTxt.setText("");
        this.ToDateTxt.setText("");
        this.TotalDayTxt.setText("");
    }//GEN-LAST:event_ClearButActionPerformed

    private void BookButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BookButActionPerformed
        try
        {
            //Get the text in text field
            String book_id = BookIDTxt.getText().trim();
            String name = NameTxt.getText().trim();
            String ic = ICTxt.getText().trim();
            String phnum = PhNumTxt.getText().trim();
            String email = EmailTxt.getText().trim();
            String room_id = RoomIDTxt.getText().trim();
            String datestart = FromDateTxt.getText().trim();
            String dateend = ToDateTxt.getText().trim();
            String totalday = TotalDayTxt.getText().trim();
            
            //add booking_2 detail to booking.txt
            try (PrintWriter book_2 = new PrintWriter(new BufferedWriter(new FileWriter("booking_2.txt", true))))
            {
                //Write data in booking.txt
                book_2.print(book_id + ",");
                book_2.print(name + ",");
                book_2.print(ic + ",");
                book_2.print(phnum  + ",");
                book_2.print(email + ",");
                book_2.print(room_id + ",");
                book_2.print(datestart + ",");
                book_2.print(dateend + ",");
                book_2.println(totalday);
                book_2.close();
            }
            catch (Exception e)
            {
                System.out.println("Error");
            }

            //make text field empty & show message
            JOptionPane.showMessageDialog(null, "Booking has been add!!!");
            this.BookIDTxt.setText("");
            this.NameTxt.setText(""); 
            this.ICTxt.setText("");
            this.PhNumTxt.setText("");
            this.EmailTxt.setText("");
            this.RoomIDTxt.setText("");
            this.FromDateTxt.setText("");
            this.ToDateTxt.setText("");
            this.TotalDayTxt.setText("");            
        }
        catch(Exception e)
        {
            System.out.println("Error");
        }
    }//GEN-LAST:event_BookButActionPerformed

    private void FromDateButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FromDateButActionPerformed
        String selectdatefrom = ((JTextField)FromDate_chooser.getDateEditor().getUiComponent()).getText();
        
        FromDateTxt.setText(selectdatefrom);
        
    }//GEN-LAST:event_FromDateButActionPerformed

    private void ToDateButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ToDateButActionPerformed
        String selectdateto = ((JTextField)ToDate_chooser.getDateEditor().getUiComponent()).getText();
        
        ToDateTxt.setText(selectdateto);
    }//GEN-LAST:event_ToDateButActionPerformed

    private void TotalDayButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TotalDayButActionPerformed
        //get date
        String fromdate = ((JTextField)FromDate_chooser.getDateEditor().getUiComponent()).getText();
        String todate = ((JTextField)ToDate_chooser.getDateEditor().getUiComponent()).getText();
        
        LocalDate fday = LocalDate.parse(fromdate);
        LocalDate tday = LocalDate.parse(todate);
        
        //count date between start to end
        Long day_gap = ChronoUnit.DAYS.between(fday, tday);
        TotalDayTxt.setText(String.valueOf(day_gap));
        
    }//GEN-LAST:event_TotalDayButActionPerformed

    private void BackBookRoomButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackBookRoomButActionPerformed
        this.setVisible(false);
        function f= new function();
        f.setVisible(true);
    }//GEN-LAST:event_BackBookRoomButActionPerformed

    private void ComfirmRoomButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComfirmRoomButActionPerformed
        RoomIDTxt.setText(RoomIDComboBox.getSelectedItem().toString());
    }//GEN-LAST:event_ComfirmRoomButActionPerformed

    private void CheckRoomButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckRoomButActionPerformed
        try
        {            
            String check_room_id = RoomIDTxt.getText();
            String datestart = FromDateTxt.getText();
            Date date1 = new SimpleDateFormat("yyyy-MM-dd").parse(datestart);
            //boolean flag = false;
            //int count = 0;
            
            try
            {
                File file = new File("booking_2.txt");
                Scanner s = new Scanner(file);

                //String line;
                //String[] lineArr;
                String DateInFile;

                while(s.hasNext())
                {
                    String line = s.nextLine();
                    
                    if (line.contains(check_room_id))
                    {
                        //lineArr[0].equals(check_room_id)
                        System.out.println(line);
                        String [] split = line.split(",");
                        DateInFile = split[7];
                        Date date2 = new SimpleDateFormat("yyyy-MM-dd").parse(DateInFile);
                        
                        int result = date1.compareTo(date2);
                        
                        if (result < 0) 
                        {
                            JOptionPane.showMessageDialog(null, "Please choose another room \nThis room is not available !!!", "Error Message", JOptionPane.ERROR_MESSAGE);
                            this.RoomIDTxt.setText("");
                            this.FromDateTxt.setText("");
                            this.ToDateTxt.setText("");
                            this.TotalDayTxt.setText("");
                        } 
                        else if (result == 0) {
                            JOptionPane.showMessageDialog(null, "Please choose another room \nThis room is not available !!!", "Error Message", JOptionPane.ERROR_MESSAGE);
                            this.RoomIDTxt.setText("");
                            this.FromDateTxt.setText("");
                            this.ToDateTxt.setText("");
                            this.TotalDayTxt.setText("");
                        }
                        else if (result > 0) {
                            JOptionPane.showMessageDialog(null, "The room is available!!!");
                        }
                    }
                }
            }
            catch(Exception e)
            {
                System.out.println("Error-1");
            }
        }
        catch(Exception e)
        {
            System.out.println("Error");
        }
    }//GEN-LAST:event_CheckRoomButActionPerformed

    private void CheckBookIDButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckBookIDButActionPerformed
        try
        {            
            String check_book_id = BookIDTxt.getText();
            boolean flag = false;
            int count = 0;
            
            Scanner sc = new Scanner(new FileInputStream("booking_2.txt"));
            while(sc.hasNextLine()) {
               String line = sc.nextLine();
               if(line.contains(check_book_id)) {
                  flag = true;
                  count = count+1;
               }
            }
            if(flag) 
            {
                JOptionPane.showMessageDialog(null, "Please choose another book ID \nThis book ID have been use !!!", "Error Message", JOptionPane.ERROR_MESSAGE);
                this.BookIDTxt.setText("");
            } 
            else 
            {
               JOptionPane.showMessageDialog(null, "This book ID is available");
            }
        }
        catch(Exception e)
        {
            System.out.println("Error");
        }
    }//GEN-LAST:event_CheckBookIDButActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BookRoom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BookRoom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BookRoom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BookRoom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BookRoom().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackBookRoomBut;
    private javax.swing.JButton BookBut;
    private javax.swing.JLabel BookIDLab;
    private javax.swing.JTextField BookIDTxt;
    private javax.swing.JLabel BookRoomLab;
    private javax.swing.JButton CheckBookIDBut;
    private javax.swing.JButton CheckRoomBut;
    private javax.swing.JButton ClearBut;
    private javax.swing.JButton ComfirmRoomBut;
    private javax.swing.JLabel EmailLab;
    private javax.swing.JTextField EmailTxt;
    private javax.swing.JButton FromDateBut;
    private javax.swing.JLabel FromDateLab;
    private javax.swing.JTextField FromDateTxt;
    private com.toedter.calendar.JDateChooser FromDate_chooser;
    private javax.swing.JLabel ICLab;
    private javax.swing.JTextField ICTxt;
    private javax.swing.JLabel NameLab;
    private javax.swing.JTextField NameTxt;
    private javax.swing.JLabel PhNumLab;
    private javax.swing.JTextField PhNumTxt;
    private javax.swing.JComboBox<String> RoomIDComboBox;
    private javax.swing.JLabel RoomIDLab;
    private javax.swing.JTextField RoomIDTxt;
    private javax.swing.JButton ToDateBut;
    private javax.swing.JTextField ToDateTxt;
    private com.toedter.calendar.JDateChooser ToDate_chooser;
    private javax.swing.JButton TotalDayBut;
    private javax.swing.JLabel TotalDayLab;
    private javax.swing.JTextField TotalDayTxt;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
