/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package js_room_booking;

/**
 *
 * @author Conan
 */
public class function extends javax.swing.JFrame {

    /**
     * Creates new form function
     */
    public function() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SelectLab = new javax.swing.JLabel();
        BookRoomBut = new javax.swing.JButton();
        ManageRoomBut = new javax.swing.JButton();
        ReceiptBut = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        SelectLab.setFont(new java.awt.Font("Neue Haas Grotesk Text Pro", 1, 48)); // NOI18N
        SelectLab.setText("Please Select");

        BookRoomBut.setBackground(new java.awt.Color(248, 195, 121));
        BookRoomBut.setFont(new java.awt.Font("Neue Haas Grotesk Text Pro", 1, 36)); // NOI18N
        BookRoomBut.setForeground(new java.awt.Color(93, 55, 10));
        BookRoomBut.setText("Book Room");
        BookRoomBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BookRoomButActionPerformed(evt);
            }
        });

        ManageRoomBut.setBackground(new java.awt.Color(248, 195, 121));
        ManageRoomBut.setFont(new java.awt.Font("Neue Haas Grotesk Text Pro", 1, 36)); // NOI18N
        ManageRoomBut.setForeground(new java.awt.Color(93, 55, 10));
        ManageRoomBut.setText("Manage Room Booking");
        ManageRoomBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManageRoomButActionPerformed(evt);
            }
        });

        ReceiptBut.setBackground(new java.awt.Color(248, 195, 121));
        ReceiptBut.setFont(new java.awt.Font("Neue Haas Grotesk Text Pro", 1, 36)); // NOI18N
        ReceiptBut.setForeground(new java.awt.Color(93, 55, 10));
        ReceiptBut.setText("Receipt");
        ReceiptBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReceiptButActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(SelectLab)
                .addGap(100, 100, 100))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ManageRoomBut)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(103, 103, 103)
                                .addComponent(BookRoomBut))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(174, 174, 174)
                        .addComponent(ReceiptBut)))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(SelectLab)
                .addGap(18, 18, 18)
                .addComponent(ReceiptBut)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BookRoomBut)
                .addGap(18, 18, 18)
                .addComponent(ManageRoomBut)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BookRoomButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BookRoomButActionPerformed
        this.setVisible(false);
        BookRoom br = new BookRoom();
        br.setVisible(true);
    }//GEN-LAST:event_BookRoomButActionPerformed

    private void ManageRoomButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManageRoomButActionPerformed
        this.setVisible(false);
        ManageRoomBooking mrb = new ManageRoomBooking();
        mrb.setVisible(true);
    }//GEN-LAST:event_ManageRoomButActionPerformed

    private void ReceiptButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReceiptButActionPerformed
        this.setVisible(false);
        receipt rc = new receipt();
        rc.setVisible(true);
    }//GEN-LAST:event_ReceiptButActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(function.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(function.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(function.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(function.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new function().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BookRoomBut;
    private javax.swing.JButton ManageRoomBut;
    private javax.swing.JButton ReceiptBut;
    private javax.swing.JLabel SelectLab;
    // End of variables declaration//GEN-END:variables
}
