/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package js_room_booking;

import javax.swing.*;

public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        WelcomeLab = new javax.swing.JLabel();
        StaffNameTxt = new javax.swing.JTextField();
        LoginLab = new javax.swing.JLabel();
        StaffPassTxt = new javax.swing.JTextField();
        StaffNameLab = new javax.swing.JLabel();
        StaffPassLab = new javax.swing.JLabel();
        LoginBut = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        WelcomeLab.setFont(new java.awt.Font("Neue Haas Grotesk Text Pro", 3, 24)); // NOI18N
        WelcomeLab.setText("Welcom to JS Resort Room Booking System");

        StaffNameTxt.setFont(new java.awt.Font("Neue Haas Grotesk Text Pro", 0, 14)); // NOI18N
        StaffNameTxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        LoginLab.setFont(new java.awt.Font("Neue Haas Grotesk Text Pro", 1, 36)); // NOI18N
        LoginLab.setForeground(new java.awt.Color(153, 51, 255));
        LoginLab.setText("Please Login");

        StaffPassTxt.setFont(new java.awt.Font("Neue Haas Grotesk Text Pro", 0, 14)); // NOI18N
        StaffPassTxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        StaffNameLab.setFont(new java.awt.Font("Neue Haas Grotesk Text Pro", 1, 24)); // NOI18N
        StaffNameLab.setForeground(new java.awt.Color(0, 0, 204));
        StaffNameLab.setText("Name:");

        StaffPassLab.setFont(new java.awt.Font("Neue Haas Grotesk Text Pro", 1, 24)); // NOI18N
        StaffPassLab.setForeground(new java.awt.Color(0, 0, 204));
        StaffPassLab.setText("Password:");

        LoginBut.setBackground(new java.awt.Color(0, 0, 0));
        LoginBut.setFont(new java.awt.Font("Neue Haas Grotesk Text Pro", 3, 18)); // NOI18N
        LoginBut.setForeground(new java.awt.Color(255, 255, 255));
        LoginBut.setText("LOGIN");
        LoginBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginButActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(StaffPassLab)
                            .addComponent(StaffNameLab, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(StaffPassTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(StaffNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(154, 154, 154)
                        .addComponent(LoginLab)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(LoginBut)
                    .addComponent(WelcomeLab))
                .addGap(22, 22, 22))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(WelcomeLab)
                .addGap(36, 36, 36)
                .addComponent(LoginLab)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(StaffNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(StaffNameLab))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(StaffPassLab)
                    .addComponent(StaffPassTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addComponent(LoginBut)
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LoginButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginButActionPerformed
        String name = StaffNameTxt.getText();
        String pass = StaffPassTxt.getText();
        
        if (name.contains("admin") && pass.contains("123"))
        {
            function f= new function();
            f.setVisible(true);
            dispose();
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Wrong Name or Password! \nTry Again!!!", "Error Message", JOptionPane.ERROR_MESSAGE);
            StaffNameTxt.setText("");
            StaffPassTxt.setText("");
        }
        
    }//GEN-LAST:event_LoginButActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton LoginBut;
    private javax.swing.JLabel LoginLab;
    private javax.swing.JLabel StaffNameLab;
    private javax.swing.JTextField StaffNameTxt;
    private javax.swing.JLabel StaffPassLab;
    private javax.swing.JTextField StaffPassTxt;
    private javax.swing.JLabel WelcomeLab;
    // End of variables declaration//GEN-END:variables
}
