/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package js_room_booking;

/**
 *
 * @author Conan
 */
public class ManageRoomBooking extends javax.swing.JFrame {

    /**
     * Creates new form manage_rom_booking
     */
    public ManageRoomBooking() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ManageRoomLab = new javax.swing.JLabel();
        DeleteBut = new javax.swing.JButton();
        SearchViewBut = new javax.swing.JButton();
        BackManageRoomBut = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ManageRoomLab.setFont(new java.awt.Font("Neue Haas Grotesk Text Pro", 1, 45)); // NOI18N
        ManageRoomLab.setText("Manage Room Booking");

        DeleteBut.setBackground(new java.awt.Color(145, 205, 145));
        DeleteBut.setFont(new java.awt.Font("Neue Haas Grotesk Text Pro", 3, 30)); // NOI18N
        DeleteBut.setForeground(new java.awt.Color(23, 107, 23));
        DeleteBut.setText("Delete Booking");
        DeleteBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteButActionPerformed(evt);
            }
        });

        SearchViewBut.setBackground(new java.awt.Color(194, 167, 222));
        SearchViewBut.setFont(new java.awt.Font("Neue Haas Grotesk Text Pro", 3, 30)); // NOI18N
        SearchViewBut.setForeground(new java.awt.Color(99, 30, 145));
        SearchViewBut.setText("Search & View & Modify Booking");
        SearchViewBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchViewButActionPerformed(evt);
            }
        });

        BackManageRoomBut.setBackground(new java.awt.Color(0, 0, 0));
        BackManageRoomBut.setFont(new java.awt.Font("Neue Haas Grotesk Text Pro", 1, 14)); // NOI18N
        BackManageRoomBut.setForeground(new java.awt.Color(255, 255, 255));
        BackManageRoomBut.setText("BACK");
        BackManageRoomBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackManageRoomButActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(BackManageRoomBut)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(ManageRoomLab))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(120, 120, 120)
                                .addComponent(DeleteBut)
                                .addGap(118, 118, 118))
                            .addComponent(SearchViewBut))))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ManageRoomLab)
                .addGap(31, 31, 31)
                .addComponent(DeleteBut)
                .addGap(38, 38, 38)
                .addComponent(SearchViewBut)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(BackManageRoomBut))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SearchViewButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchViewButActionPerformed
        this.setVisible(false);
        B_Search_View_Modify sv = new B_Search_View_Modify();
        sv.setVisible(true);
    }//GEN-LAST:event_SearchViewButActionPerformed

    private void DeleteButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteButActionPerformed
        this.setVisible(false);
        B_Delete d = new B_Delete();
        d.setVisible(true);
    }//GEN-LAST:event_DeleteButActionPerformed

    private void BackManageRoomButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackManageRoomButActionPerformed
        this.setVisible(false);
        function f = new function();
        f.setVisible(true);
    }//GEN-LAST:event_BackManageRoomButActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageRoomBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageRoomBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageRoomBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageRoomBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageRoomBooking().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackManageRoomBut;
    private javax.swing.JButton DeleteBut;
    private javax.swing.JLabel ManageRoomLab;
    private javax.swing.JButton SearchViewBut;
    // End of variables declaration//GEN-END:variables
}
