/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package js_room_booking;

import java.io.*;
import java.util.*;
import javax.swing.*;

/**
 *
 * @author Conan
 */
public class receipt extends javax.swing.JFrame {

    /**
     * Creates new form receipt
     */
    public receipt() {
        initComponents();
        
        //unable edit in text field
        NameTxt.setEditable(false);
        ICTxt.setEditable(false);
        PHNumTxt.setEditable(false);
        EmailTxt.setEditable(false);
        RoomIDTxt.setEditable(false);
        FromDateTxt.setEditable(false);
        ToDateTxt.setEditable(false);
        TotalDayTxt.setEditable(false);
        TotalPriceTxt.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        BookIDLab = new javax.swing.JLabel();
        BookIDTxt = new javax.swing.JTextField();
        SearchBut = new javax.swing.JButton();
        NameLab = new javax.swing.JLabel();
        ICLab = new javax.swing.JLabel();
        EmailLab = new javax.swing.JLabel();
        PHNumLab = new javax.swing.JLabel();
        RoomIDLab = new javax.swing.JLabel();
        FromDateLab = new javax.swing.JLabel();
        ToDtaeLab = new javax.swing.JLabel();
        NameTxt = new javax.swing.JTextField();
        ICTxt = new javax.swing.JTextField();
        PHNumTxt = new javax.swing.JTextField();
        EmailTxt = new javax.swing.JTextField();
        RoomIDTxt = new javax.swing.JTextField();
        FromDateTxt = new javax.swing.JTextField();
        ToDateTxt = new javax.swing.JTextField();
        BackBut = new javax.swing.JButton();
        TotalBut = new javax.swing.JButton();
        TotalDayLab = new javax.swing.JLabel();
        TotalDayTxt = new javax.swing.JTextField();
        TotalPriceTxt = new javax.swing.JTextField();
        TotalPriceLab = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Neue Haas Grotesk Text Pro", 1, 36)); // NOI18N
        jLabel1.setText("Receipt");

        BookIDLab.setFont(new java.awt.Font("Neue Haas Grotesk Text Pro", 1, 24)); // NOI18N
        BookIDLab.setText("Book ID :");

        BookIDTxt.setFont(new java.awt.Font("Neue Haas Grotesk Text Pro", 0, 18)); // NOI18N

        SearchBut.setBackground(new java.awt.Color(255, 185, 185));
        SearchBut.setFont(new java.awt.Font("Neue Haas Grotesk Text Pro", 3, 14)); // NOI18N
        SearchBut.setForeground(new java.awt.Color(79, 137, 109));
        SearchBut.setText("SEARCH");
        SearchBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchButActionPerformed(evt);
            }
        });

        NameLab.setFont(new java.awt.Font("Neue Haas Grotesk Text Pro", 1, 18)); // NOI18N
        NameLab.setText("Name :");

        ICLab.setFont(new java.awt.Font("Neue Haas Grotesk Text Pro", 1, 18)); // NOI18N
        ICLab.setText("IC :");

        EmailLab.setFont(new java.awt.Font("Neue Haas Grotesk Text Pro", 1, 18)); // NOI18N
        EmailLab.setText("Email :");

        PHNumLab.setFont(new java.awt.Font("Neue Haas Grotesk Text Pro", 1, 18)); // NOI18N
        PHNumLab.setText("PH Number :");

        RoomIDLab.setFont(new java.awt.Font("Neue Haas Grotesk Text Pro", 1, 18)); // NOI18N
        RoomIDLab.setText("Room ID :");

        FromDateLab.setFont(new java.awt.Font("Neue Haas Grotesk Text Pro", 1, 18)); // NOI18N
        FromDateLab.setText("From Date :");

        ToDtaeLab.setFont(new java.awt.Font("Neue Haas Grotesk Text Pro", 1, 18)); // NOI18N
        ToDtaeLab.setText("To Date :");

        NameTxt.setFont(new java.awt.Font("Neue Haas Grotesk Text Pro", 0, 14)); // NOI18N

        ICTxt.setFont(new java.awt.Font("Neue Haas Grotesk Text Pro", 0, 14)); // NOI18N

        PHNumTxt.setFont(new java.awt.Font("Neue Haas Grotesk Text Pro", 0, 14)); // NOI18N

        EmailTxt.setFont(new java.awt.Font("Neue Haas Grotesk Text Pro", 0, 14)); // NOI18N

        RoomIDTxt.setFont(new java.awt.Font("Neue Haas Grotesk Text Pro", 0, 14)); // NOI18N

        FromDateTxt.setFont(new java.awt.Font("Neue Haas Grotesk Text Pro", 0, 14)); // NOI18N

        ToDateTxt.setFont(new java.awt.Font("Neue Haas Grotesk Text Pro", 0, 14)); // NOI18N

        BackBut.setBackground(new java.awt.Color(0, 0, 0));
        BackBut.setFont(new java.awt.Font("Neue Haas Grotesk Text Pro", 1, 14)); // NOI18N
        BackBut.setForeground(new java.awt.Color(255, 255, 255));
        BackBut.setText("BACK");
        BackBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButActionPerformed(evt);
            }
        });

        TotalBut.setBackground(new java.awt.Color(103, 40, 8));
        TotalBut.setFont(new java.awt.Font("Neue Haas Grotesk Text Pro", 3, 18)); // NOI18N
        TotalBut.setForeground(new java.awt.Color(254, 218, 200));
        TotalBut.setText("TOTAL");
        TotalBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TotalButActionPerformed(evt);
            }
        });

        TotalDayLab.setFont(new java.awt.Font("Neue Haas Grotesk Text Pro", 1, 18)); // NOI18N
        TotalDayLab.setText("Total Day :");

        TotalPriceTxt.setFont(new java.awt.Font("Neue Haas Grotesk Text Pro", 0, 18)); // NOI18N

        TotalPriceLab.setFont(new java.awt.Font("Neue Haas Grotesk Text Pro", 1, 24)); // NOI18N
        TotalPriceLab.setText("Total Price (RM) :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addComponent(jLabel1))
                    .addComponent(BackBut)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addComponent(TotalBut)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 61, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(BookIDLab)
                                .addGap(6, 6, 6))
                            .addComponent(PHNumLab)
                            .addComponent(EmailLab)
                            .addComponent(FromDateLab)
                            .addComponent(RoomIDLab)
                            .addComponent(ICLab)
                            .addComponent(NameLab)
                            .addComponent(ToDtaeLab)
                            .addComponent(TotalDayLab))
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(BookIDTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(RoomIDTxt, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(EmailTxt, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(PHNumTxt, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(ICTxt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(FromDateTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(TotalDayTxt, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(ToDateTxt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(NameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(56, 56, 56))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(TotalPriceLab)
                        .addGap(95, 95, 95))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(TotalPriceTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(139, 139, 139))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(SearchBut)
                        .addGap(35, 35, 35))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BookIDLab)
                    .addComponent(BookIDTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addComponent(SearchBut)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NameLab)
                    .addComponent(NameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ICLab)
                    .addComponent(ICTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PHNumLab)
                    .addComponent(PHNumTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EmailLab)
                    .addComponent(EmailTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RoomIDLab)
                    .addComponent(RoomIDTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FromDateLab)
                    .addComponent(FromDateTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ToDtaeLab)
                    .addComponent(ToDateTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TotalDayTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TotalDayLab))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(BackBut)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(TotalBut)
                        .addGap(18, 18, 18)
                        .addComponent(TotalPriceLab)
                        .addGap(18, 18, 18)
                        .addComponent(TotalPriceTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(46, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SearchButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchButActionPerformed
        try
        {
            File file = new File("booking_2.txt");
            Scanner s = new Scanner(file);
            String BookID = BookIDTxt.getText();
            
            while (s.hasNext())
            {
                String line = s.nextLine();
                
                //read book id in the file
                if (line.contains(BookID))
                {
                    //line = selected row
                    //System.out.println(line);
                    String [] split = line.split(",");
                    
                    //print data
                    NameTxt.setText(split[1]);
                    ICTxt.setText(split[2]);
                    PHNumTxt.setText(split[3]);
                    EmailTxt.setText(split[4]);
                    RoomIDTxt.setText(split[5]);
                    FromDateTxt.setText(split[6]);
                    ToDateTxt.setText(split[7]);
                    TotalDayTxt.setText(split[8]);
                }
            }
        }
        catch (Exception e)
        {
            System.out.println("Error");
        }      
    }//GEN-LAST:event_SearchButActionPerformed

    private void BackButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButActionPerformed
        this.setVisible(false);
        function f= new function();
        f.setVisible(true);
    }//GEN-LAST:event_BackButActionPerformed

    private void TotalButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TotalButActionPerformed
        try
        {
            //Get the text in text field
            String totalday = TotalDayTxt.getText().trim();
            String empty = "";
            if (totalday.equals(empty))
            {
                JOptionPane.showMessageDialog(null, "Please enter Book ID !!!", "Error Message", JOptionPane.ERROR_MESSAGE);
            }

            else{
                int days = Integer.parseInt(totalday);

                //calculate price
                int room_price = days * 350; 
                int service_tax = room_price / 10;
                int tuorism_tax = days * 10;
                int TotalPrice = service_tax + tuorism_tax + room_price;

                //show data
                TotalPriceTxt.setText("" + TotalPrice);
            }
        }
        catch (Exception e)
        {
            System.out.println("Error");
        }
    }//GEN-LAST:event_TotalButActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(receipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(receipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(receipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(receipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new receipt().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackBut;
    private javax.swing.JLabel BookIDLab;
    private javax.swing.JTextField BookIDTxt;
    private javax.swing.JLabel EmailLab;
    private javax.swing.JTextField EmailTxt;
    private javax.swing.JLabel FromDateLab;
    private javax.swing.JTextField FromDateTxt;
    private javax.swing.JLabel ICLab;
    private javax.swing.JTextField ICTxt;
    private javax.swing.JLabel NameLab;
    private javax.swing.JTextField NameTxt;
    private javax.swing.JLabel PHNumLab;
    private javax.swing.JTextField PHNumTxt;
    private javax.swing.JLabel RoomIDLab;
    private javax.swing.JTextField RoomIDTxt;
    private javax.swing.JButton SearchBut;
    private javax.swing.JTextField ToDateTxt;
    private javax.swing.JLabel ToDtaeLab;
    private javax.swing.JButton TotalBut;
    private javax.swing.JLabel TotalDayLab;
    private javax.swing.JTextField TotalDayTxt;
    private javax.swing.JLabel TotalPriceLab;
    private javax.swing.JTextField TotalPriceTxt;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
